# Generated by Django 4.1.7 on 2023-07-03 08:58

import auth_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import marketplace.models_base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, default=0.0, verbose_name='Баланс, в рублях')),
                ('first_name', models.CharField(blank=True, default='', max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, verbose_name=',Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=25, verbose_name='Отчество')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Мужчина'), ('Female', 'Женщина')], max_length=6, verbose_name='Пол')),
                ('avatar', models.ImageField(blank=True, upload_to=auth_user.models.get_image_path_for_stash, verbose_name='Аватар')),
                ('invite_code', models.CharField(blank=True, default='', max_length=12, verbose_name='Личный код приглашения')),
                ('born', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(marketplace.models_base.StringGeneratorHelperMixin, models.Model),
        ),
    ]
