# Generated by Django 4.1.7 on 2023-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='born',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
