# Generated by Django 4.1.7 on 2023-06-30 08:53

from django.db import migrations, models
import marketplace.models_base


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_shop_name_alter_shop_name_short'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentshopproduct',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='stash',
            options={'verbose_name': 'Продукт в магазине', 'verbose_name_plural': 'Продукты в магазине'},
        ),
        migrations.RemoveField(
            model_name='confidentialinfoshop',
            name='balance',
        ),
        migrations.AddField(
            model_name='shop',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Баланс магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models_base.get_image_path_for_shop, verbose_name='Аватар магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='cred_num',
            field=models.CharField(blank=True, default='', editable=False, max_length=12, unique=True, verbose_name='Внутренний номер счета'),
        ),
        migrations.AlterField(
            model_name='stash',
            name='article',
            field=models.CharField(blank=True, default='', editable=False, max_length=15, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='stash',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models_base.get_image_path_for_stash, verbose_name='Изображение товара'),
        ),
    ]
